// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBE2h6EmRlQ2FN1lPHxN7Q5rDgLOXK927A',
    appId: '1:322121757432:web:5d2c7e67acebb5fc7dc10d',
    messagingSenderId: '322121757432',
    projectId: 'tracker-f088e',
    authDomain: 'tracker-f088e.firebaseapp.com',
    storageBucket: 'tracker-f088e.appspot.com',
    measurementId: 'G-C6F1SF5EH8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_D-wEj8V5Y0scG9D0apMXvNolQFhvgJU',
    appId: '1:322121757432:android:ac90a6199093e7ed7dc10d',
    messagingSenderId: '322121757432',
    projectId: 'tracker-f088e',
    storageBucket: 'tracker-f088e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfH2GDinqf-bxZ-2VlRhF-HpMIrfu0HCg',
    appId: '1:322121757432:ios:b00a1cccefa833f67dc10d',
    messagingSenderId: '322121757432',
    projectId: 'tracker-f088e',
    storageBucket: 'tracker-f088e.appspot.com',
    androidClientId: '322121757432-h7iaum1rga0hchka1c539hfu0jsqvpe4.apps.googleusercontent.com',
    iosClientId: '322121757432-8pl42qm2bqaru4s6qof0sp81gpn30ji6.apps.googleusercontent.com',
    iosBundleId: 'com.mayank.tracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCfH2GDinqf-bxZ-2VlRhF-HpMIrfu0HCg',
    appId: '1:322121757432:ios:d1e6b11ccd7fded07dc10d',
    messagingSenderId: '322121757432',
    projectId: 'tracker-f088e',
    storageBucket: 'tracker-f088e.appspot.com',
    androidClientId: '322121757432-h7iaum1rga0hchka1c539hfu0jsqvpe4.apps.googleusercontent.com',
    iosClientId: '322121757432-cmpbbm5agilbci1aa04h3u0r2q5hfsts.apps.googleusercontent.com',
    iosBundleId: 'com.mayank.tracker.RunnerTests',
  );
}
